name: ci

on:
  push:
    branches:
      - 'main'
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 720
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v2
        env:
          TAG_NAME: riscv_linux_toolset:v1
        with:
          context: .
          push: true
          tags: |
            armleo/riscv_linux_toolset:v2
            armleo/riscv_linux_toolset:latest
