name: ci

on:
  push:
    branches:
      - 'main'
jobs:
  build-and-push-buildroot-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 720
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker Buildroot image to DockerHub
        uses: docker/build-push-action@v2
        env:
          TAG_NAME: riscv_linux_toolset:latest-buildroot
        with:
          file: Dockerfile.buildroot
          context: .
          push: true
          tags: |
            armleo/riscv_linux_toolset:buildroot-latest
            armleo/riscv_linux_toolset:buildroot-v2
  build-and-push-yocto-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 720
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker Yocto image to DockerHub
        uses: docker/build-push-action@v2
        env:
          TAG_NAME: riscv_linux_toolset:latest-yocto
        with:
          file: Dockerfile.yocto
          context: .
          push: true
          tags: |
            armleo/riscv_linux_toolset:yocto-latest
            armleo/riscv_linux_toolset:yocto-v2
